api_access/urls.py
from django.urls import path

from .views import order_list

app_name = 'api_access'


urlpatterns = [
    path(r'get-order-list/', order_list, name='order_list'),
]

itorum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'))),
    path('api/', include(('api_access.urls', 'api_access'))),
    path('order/', include(('order.urls', 'order'))),
]

order/urls.py
from django.urls import path

from .views import CreateOrderView, orderstat_by_month, DeleteOrderView

app_name = 'order'


urlpatterns = [
    path(r'create/', CreateOrderView.as_view(), name='create'),
    path(r'create.json', CreateOrderView.as_view(), kwargs={'is_json': True}, name='create_json'),
    path(r'', orderstat_by_month, name='list'),
    path(r'delete/<int:pk>', DeleteOrderView.as_view(), name='delete')
]

user/urls.py
from django.urls import path

from .views import UserDetailView, UserLoginView, UserLogoutView, home_user_page, UserHomeJsonView

app_name = 'users'


urlpatterns = [
    path(r'login/', UserLoginView.as_view(), name='login'),
    path(r'detail/<slug:slug>', UserDetailView.as_view(), name='detail'),
    path(r'logout/', UserLogoutView.as_view(), name='logout'),
    path(r'home/', home_user_page, name='home'),
    path(r'home.json', UserHomeJsonView.as_view(), name='home_json'),
]

api_access/models.py
from django.db import models

customer/models.py
from django.db import models


class Customer(models.Model):
    name = models.CharField(unique=True, verbose_name='Заказчик', max_length=50)

    def __str__(self):
        return self.name

    def to_json(self):
        return {
            "id": int(self.id),
            "name": str(self.name)
        }

order/models.py
from django.db import models

from user.models import User
from customer.models import Customer


class Order(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='orders',
        verbose_name='исполнитель'
    )
    date = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Заказчик')
    price = models.DecimalField(verbose_name='Цена', decimal_places=2, max_digits=8, default=0)

    def to_json(self):
        return {
            "id": str(self.id),
            "user": str(self.user),
            "date": str(self.date),
            "customer": self.customer.to_json(),
            "price": float(self.price)
        }

    def __str__(self):
        return f'Исполнитель: {self.user}, дата создания: {self.date}, заказчик: {self.customer}, цена: {self.price}'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import validate_slug
from django.urls import reverse_lazy


class User(AbstractUser):
    username = models.CharField(
        verbose_name="Имя пользоваталя",
        max_length=25,
        unique=True,
        validators=[validate_slug],
        error_messages={
            "unique": "К сожалению пользователь с таким имененем уже существует",
        },
    )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse_lazy('users:detail', args=[self.username])

    def get_home_url(self):
        return reverse_lazy('users:home')

order/forms.py
from django.forms import ModelForm

from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'price']

api_access/views.py
import json

from django.conf import settings
from django.http import JsonResponse, HttpResponse

from http_basic_auth import parse_header

from order.models import Order


def order_list(request):
    if 'Authorization' not in request.META:
        return HttpResponse('Unauthorized', status=401)

    authorization = request.META['Authorization']
    user, password = parse_header(authorization)

    if user not in settings.HTTP_BASIC_AUTH:
        return HttpResponse('Unauthorized', status=401)

    if settings.HTTP_BASIC_AUTH[user] != password:
        return HttpResponse('Unauthorized', status=401)

    orders = [o.to_json() for o in Order.objects.all()]
    return JsonResponse(json.dumps(orders), safe=False)

customer/views.py
from django.shortcuts import render

# Create your views here.

order/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import FormView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import OrderForm
from .models import Order

from collections import defaultdict
from datetime import date


class CreateOrderView(LoginRequiredMixin, FormView):
    form_class = OrderForm
    success_url = '/user/home'

    def form_valid(self, form):
        order = form.save(commit=False)
        order.user = self.request.user
        order.save()

        if self.kwargs.get('is_json'):
            return JsonResponse(order.to_json())

        return redirect(self.request.user.get_home_url())


def orderstat_by_month(request):
    orders = Order.objects.filter(date__month=date.today().month).order_by('date')
    by_weeks = defaultdict(list)
    data =[]

    for order in orders:
        by_weeks[order.date.isocalendar()[1]].append(order)
    weeks = by_weeks.values()

    for week in weeks:
        by_day = defaultdict(list)
        for order in week:
            by_day[order.date.date()].append(order)
        data_by_day = {}
        for key, value in by_day.items():
            data_by_day[key] = get_stat(value)
        data.append(data_by_day)

    return render(request, 'order/order_stat_list_month.html', {'order_stat_by_weeks': data})


def get_stat(orders):
    end_price = 0
    users = set()

    for order in orders:
        users.add(order.user)
        end_price += order.price

    return {'users': users, 'end_price': end_price}


class DeleteOrderView(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = '/user/home'

user/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.http import JsonResponse
from django.shortcuts import reverse, HttpResponseRedirect, render
from django.views.generic import DetailView, View

from user.models import User
from order.models import Order
from order.forms import OrderForm


class UserDetailView(DetailView):
    model = User
    slug_field = "username"

    def get_context_data(self, **kwargs):
        ctx = super(UserDetailView, self).get_context_data(**kwargs)
        user = self.request.user
        ctx['orders'] = Order.objects.filter(user=user)
        return ctx


class UserLoginView(LoginView):
    template_name = 'user/user_login.html'


class UserLogoutView(LogoutView):

    def get(self,*args, **kwargs):
        logout(self.request)
        return HttpResponseRedirect(reverse('index'))


@login_required
def home_user_page(request):
    return render(request, 'user/user_home.html', {'orders': Order.objects.filter(user=request.user),
                                                   'form': OrderForm(),
                                                   })


class UserHomeJsonView(View):
    http_method_names = ['get']

    def get(self, request):
        return JsonResponse({'orders': [o.to_json() for o in Order.objects.filter(user=request.user)]})

order/templates/order/order_confirm_delete.html
{% extends 'index.html' %}
{% block content%}
<div>
    Вы точно хотите удалить этот заказ?
    <p>{{object}}
    <form method="post">
        <input type="submit" value="Да" class="btn btn-danger">
        <input type="submit" value="Нет" class="btn btn-primary" formaction="/user/home/">
        {%csrf_token%}
    </form>
</div>
{% endblock %}

order/templates/order/order_list.html
{% extends 'index.html' %}
{% block content%}
<ul>
    {% for key, day_orders in month_orders.items %}
        {% for order in day_orders %}
            <li>
                {{ order }}
            </li>
        {% endfor %}
    {% endfor %}
</ul>
{% endblock %}

order/templates/order/order_stat_list_month.html
{% extends 'index.html' %}
{% block content%}
    {% for week in order_stat_by_weeks %}
        <div class="btn btn-primary"
             data-toggle="collapse"
             aria-expanded="false"
             data-target="#collapseExample-{{ forloop.counter }}"
        >
                {{ forloop.counter}}-я неделя
        </div>
        <table class="table collapse" id="collapseExample-{{ forloop.counter }}">
        {% for day, stat in week.items %}
            <tr>
                <td>
                    {{day|date:'d, m , y'}}
                </td>
                <td>
                    {% for user in stat.users %}
                        {{ user }}{% if not forloop.last%}; {% endif %}
                    {% endfor %}
                </td>
                <td>
                    {{ stat.end_price}}
                </td>
            </tr>
        {% endfor %}
        </table>
    {% endfor %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

user/templates/user/user_detail.html
{% extends 'index.html' %}
{% block content%}

<h1>
    {{ object.username }}
</h1>
<ul>
{% for order in orders %}
    <li>
        <p>{{ order }}
    </li>
{% endfor %}
</ul>
{% endblock %}

user/templates/user/user_home.html
{% extends 'index.html' %}
{% block content%}

<h1>
    {{ user.username }}
</h1>
<ul class="order_list">
{% for order in orders %}
    <li>
        {{ order }}
        <a href="{%url 'order:delete' order.id%}" class="btn btn-primary">Удалить заказ</a>
    </li>
{% endfor %}
</ul>
<form method="POST" action="{% url 'order:create'%}" class="order_create_form">
    {{ form }} {% csrf_token %}
    <button class="btn btn-primary order_create_butt">Добавить заказ</button>
</form>
{% endblock %}

user/templates/user/user_login.html
{% extends 'index.html' %}
{% block content%}

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Войти</button>
</form>

{% endblock %}